use sql_practice;

/* PRIMARY KEY: A primary key can uniquely identify each row in a table*/

CREATE TABLE Constraints(id INT, Name VARCHAR(25), Contact VARCHAR(25), PRIMARY KEY(id));   /* CREATE TABLE WITH ONE COLUMN AS PRIMARY KEY*/

CREATE TABLE Constraints(id INT, Name VARCHAR(25), Contact VARCHAR(25), CONSTRAINT Person PRIMARY KEY(id, Name));    /* CREATE TABLE WITH MULTIPLE COLUMNS AS PRIMARY KEY */
/* WHEN WE WANT TO COMBINE MULTIPLE COLUMNS INTO ONE PRIMARY KEY WE HAVE TO DEFINE A CONSTRAINT  */

ALTER TABLE Constraints ADD PRIMARY KEY (id);        /* ALTER TABLE WITH SINGLE COLUMN AS PRIMARY KEY*/

ALTER TABLE Constraints ADD CONSTRAINT Person PRIMARY KEY (id, Name);       /* ALTER TABLE WITH MULTIPLE COLUMNS AS PRIMARY KEY */

ALTER TABLE Constraints DROP PRIMARY KEY;                /* DROP PRIMARY KEY(NOT COLUMN) WITH SINGLE COLUMN FROM TABLE */

ALTER TABLE Constraints DROP CONSTRAINT Person;          /* DROP PRIMARY KEY(NOT COLUMN) WITH MULTIPLE COLUMNS FROM TABLE */